namespace FundingPlatform.Application.Services;

/// <summary>
/// Spec 027 / US1 (FR-001, FR-002) — post-processes the output of
/// <see cref="IUserStoreReader.GetDisplayNameAsync"/> so the funding-agreement
/// "generated by" attribution is never a raw user identifier.
/// <para>
/// The reader's ladder is full name → email → <c>userId</c> (a GUID) for the
/// spec-017 activity-feed graceful-degradation contract. For US1 the trailing
/// GUID fallback is unacceptable, so when resolution falls through to the id
/// itself (deleted account, or empty name+email) we substitute a stable es-CR
/// label instead.
/// </para>
/// </summary>
public static class GeneratorDisplayName
{
    /// <summary>Stable es-CR label shown when the generator can no longer be resolved.</summary>
    public const string DeletedFallback = "Usuario no disponible";

    /// <summary>
    /// Maps a resolved display name to the value shown in the attribution.
    /// Returns <c>null</c> when there is no generator (no agreement yet),
    /// the stable fallback when resolution failed (null/empty, or the resolver
    /// returned the raw id), and the resolved name otherwise.
    /// </summary>
    /// <param name="resolvedName">Output of <c>GetDisplayNameAsync(generatedByUserId)</c>, or <c>null</c> when not resolved.</param>
    /// <param name="generatedByUserId">The agreement's <c>GeneratedByUserId</c>, or <c>null</c> when no agreement exists.</param>
    public static string? FromResolved(string? resolvedName, string? generatedByUserId)
    {
        if (string.IsNullOrWhiteSpace(generatedByUserId))
        {
            return null;
        }
        if (string.IsNullOrWhiteSpace(resolvedName))
        {
            return DeletedFallback;
        }
        // Resolver fell through to the id itself → no human name/email on record.
        return string.Equals(resolvedName, generatedByUserId, StringComparison.Ordinal)
            ? DeletedFallback
            : resolvedName;
    }
}
