using FundingPlatform.Application.Notifications;
using FundingPlatform.Domain.Notifications;

namespace FundingPlatform.Infrastructure.Notifications.Persistence;

/// <summary>
/// Spec 021 / T017 / FR-002 — EF-mapped outbox row. Status transitions are
/// expressed as behaviour methods so callers can't mismatch
/// <c>(Status, AttemptCount, NextAttemptAt, LastError)</c>. RowVersion is the
/// optimistic-concurrency claim guard (FR-004).
/// </summary>
public class NotificationOutbox
{
    // EF parameterless ctor — keep parameterless so the EF materializer can use it.
    private NotificationOutbox() { }

    /// <summary>Factory used by <see cref="NotificationOutboxWriter"/>.</summary>
    public static NotificationOutbox Create(
        NotificationEvent eventType,
        int applicationId,
        int versionHistoryId,
        NotificationPayload payload)
    {
        return new NotificationOutbox
        {
            EventType        = eventType.ToStorageString(),
            ApplicationId    = applicationId,
            VersionHistoryId = versionHistoryId,
            PayloadJson      = payload.Serialize(),
            CreatedAt        = DateTime.UtcNow,
            Status           = NotificationOutboxStatus.Pending,
            AttemptCount     = 0,
            LastError        = null,
            NextAttemptAt    = null,
            // RowVersion is server-generated by SQL Server (ROWVERSION). The
            // in-memory EF provider used by integration tests does not generate
            // it, so we seed an empty array as a sentinel; real SQL Server
            // replaces it with a real version stamp on insert via IsRowVersion().
            RowVersion       = Array.Empty<byte>(),
        };
    }

    /// <summary>
    /// Spec 021 — placeholder navigation that EF ignores via
    /// <c>NotificationOutboxConfiguration.Ignore</c>. Reserved for a future
    /// audit-projection seam. Not used by the runtime; setting it has no effect.
    /// </summary>
    public Domain.Entities.VersionHistory? VersionHistory { get; private set; }

    public long Id { get; private set; }

    /// <summary>Upper-snake-case storage form. Use <see cref="EventTypeEnum"/> to read as enum.</summary>
    public string EventType { get; private set; } = default!;

    /// <summary>Typed accessor over <see cref="EventType"/>.</summary>
    public NotificationEvent EventTypeEnum => NotificationEventExtensions.FromStorageString(EventType);

    public int ApplicationId { get; private set; }
    public int VersionHistoryId { get; private set; }
    public string PayloadJson { get; private set; } = default!;
    public DateTime CreatedAt { get; private set; }
    public string Status { get; private set; } = NotificationOutboxStatus.Pending;
    public int AttemptCount { get; private set; }
    public string? LastError { get; private set; }
    public DateTime? NextAttemptAt { get; private set; }
    public byte[] RowVersion { get; private set; } = default!;

    /// <summary>
    /// FR-004 — claim from <c>Pending</c> or expired <c>Dispatching</c>. RowVersion
    /// concurrency check happens at SaveChanges time; a losing claim throws
    /// <c>DbUpdateConcurrencyException</c> which the worker catches as a no-op.
    /// </summary>
    public void ClaimForDispatch()
    {
        Status = NotificationOutboxStatus.Dispatching;
        // NextAttemptAt is left untouched until a transient-failure mark.
    }

    /// <summary>FR-005 — terminal success.</summary>
    public void MarkDone()
    {
        Status = NotificationOutboxStatus.Done;
        LastError = null;
    }

    /// <summary>FR-005 / FR-021 — transient failure increments attempt count.</summary>
    public void MarkTransientFailure(string error, DateTime nextAttemptAt)
    {
        AttemptCount++;
        Status = NotificationOutboxStatus.Dispatching;
        NextAttemptAt = nextAttemptAt;
        LastError = TruncateError(error);
    }

    /// <summary>FR-005 / FR-022 — permanent failure / max-attempts reached.</summary>
    public void MarkDeadLetter(string error)
    {
        Status = NotificationOutboxStatus.DeadLetter;
        LastError = TruncateError(error);
    }

    private static string TruncateError(string error)
    {
        // dacpac column: NVARCHAR(2000). Truncate to fit per data-model.md.
        const int max = 2000;
        return error.Length <= max ? error : error[..max];
    }
}

/// <summary>
/// Spec 021 / data-model.md — string constants matching the dacpac CHECK
/// constraint on <c>NotificationOutbox.Status</c>. Kept as constants (not
/// enum) so EF stores them verbatim and operators can read raw rows.
/// </summary>
public static class NotificationOutboxStatus
{
    public const string Pending     = "Pending";
    public const string Dispatching = "Dispatching";
    public const string Done        = "Done";
    public const string DeadLetter  = "DeadLetter";
}
